version: 2.1

orbs:
    allure: ayte/allure@0.1.3
    browser-tools: circleci/browser-tools@1.4.0
    webex-orb: cxepi/webex-orb@0.3.4

jobs:
    run_tests:
        circleci_ip_ranges: true
        docker:
            - image: cimg/node:16.16.0-browsers
              environment:
                  TERM: xterm
        parameters:
            specPath:
                type: string
            userType:
                type: string
            environment:
                type: string
                default: "Test"
            browser:
                type: string
            base_url:
                type: string
                default: ${BASE_URL_TEST}
        working_directory: ~/repo
        steps:
            - checkout
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - browser-tools/install-firefox
            - browser-tools/install-geckodriver
            - allure/install
            - restore_cache:
                  name: Restore `package.json` cache
                  keys:
                      - deps-{{ .Branch }}-{{ checksum "package.json" }}
                      - deps-{{ .Branch }}
                      - deps
            - run:
                  name: Install Dependencies
                  command: |
                      npm ci
            - save_cache:
                  name: Save Cache - NPM and Cypress!
                  key: v3-deps-{{ .Branch }}-{{ checksum "package.json" }}
                  paths:
                      - ~/.npm
                      - ~/.cache/Cypress
            - run:
                  name: Install Edge Browser
                  command: |
                      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
                      sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
                      sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
                      sudo rm microsoft.gpg
                      sudo apt update
                      sudo apt install microsoft-edge-dev
                      wget https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/104.0.1271.2/edgedriver_linux64.zip -P ~/
                      unzip ~/edgedriver_linux64.zip -d ~/
                      rm ~/edgedriver_linux64.zip
                      sudo mv -f ~/msedgedriver /usr/local/share/
                      sudo chmod 777 /usr/local/share/msedgedriver
                      sudo ln -s /usr/local/share/msedgedriver /usr/local/bin/msedgedriver
            - run:
                  name: Run Cypress Tests on << parameters.browser >>
                  command: |
                      export CYPRESS_BASE_URL=<< parameters.base_url >>
                      export CYPRESS_PA_ST_ONLY_USER=${PA_ST_ONLY_USER}
                      export CYPRESS_PA_ST_HCAAS_USER=${PA_ST_HCAAS_USER}
                      export CYPRESS_PA_HCAAS_ONLY_USER=${PA_HCAAS_ONLY_USER}
                      export CYPRESS_PA_LCA_USER=${PA_LCA_USER}
                      export CYPRESS_PORTAL_PASSWORD=${PORTAL_PASSWORD}
                      npm run cy:exec -- -b "<< parameters.browser >>" -s "<< parameters.specPath >>"
            - store_test_results:
                  name: Store Test Results
                  path: results/junit
            - run:
                  name: Generate Allure Report
                  when: always
                  command: npm run report:generate
            - store_artifacts:
                  name: Store Allure Report
                  path: results/allure-report
            - webex-orb/notify:
                  message: >-
                      Hi Team, Below is the Cypress UI Automation Report on << parameters.environment >> Environment for << parameters.userType >> in "<< parameters.browser >>" browser. Circle CI Build URL - ${CIRCLE_BUILD_URL} Allure Report - https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/results/allure-report/index.html

workflows:
    run_tests_all_roles:
        jobs:
            - run_tests:
                  name: "Admin (ST Only) - chrome"
                  userType: "Admin - ST Only User"
                  specPath: "cypress/e2e/admin_st_only/**/*.feature"
                  browser: chrome
                  filters:
                      branches:
                          only:
                              - main
            - run_tests:
                  name: "Admin (HCAAS Only) - chrome"
                  userType: "Admin - HCAAS Only User"
                  specPath: "cypress/e2e/admin_hcaas_only/**/*.feature"
                  browser: chrome
                  filters:
                      branches:
                          only:
                              - main
            - run_tests:
                  name: "Admin (HCAAS + ST) - chrome"
                  userType: "Admin - HCAAS + ST User"
                  specPath: "cypress/e2e/admin_hcaas_st/**/*.feature"
                  browser: chrome
                  filters:
                      branches:
                          only:
                              - main
            - run_tests:
                  name: "Admin (LCA) - chrome"
                  userType: "Admin - LCA User"
                  specPath: "cypress/e2e/admin_lca/**/*.feature"
                  browser: chrome
                  filters:
                      branches:
                          only:
                              - main
